# SPDX-License-Identifier: GPL-3.0-only

# Name of the application's binary.
name := 'circle'
launcher := 'circle-launcher'
# The unique ID of the application.
appid := 'io.github.entro314labs.Circle'

# Path to root file system, which defaults to `/`.
rootdir := ''
# The prefix for the `/usr` directory.
prefix := '/usr'
# The location of the cargo target directory. build.rs writes the generated
# XDG files under the same root, so redirecting it keeps everything together.
cargo-target-dir := env('CARGO_TARGET_DIR', 'target')

# Sources. The desktop entry and metainfo are GENERATED by build.rs from the
# templates in `resources/` plus the Fluent catalogues in `i18n/`, so the files
# installed below only exist after a build. `install` depends on that.
desktop-src := cargo-target-dir / 'xdgen' / 'app.desktop'
metainfo-src := cargo-target-dir / 'xdgen' / 'app.metainfo.xml'
icon-src := 'resources' / 'icons' / 'hicolor' / 'scalable' / 'apps' / 'icon.svg'
launcher-plugin-src := 'resources' / 'launcher' / 'plugin.ron'

# Install destinations
base-dir := absolute_path(clean(rootdir / prefix))
bin-dst := base-dir / 'bin' / name
desktop-dst := base-dir / 'share' / 'applications' / (appid + '.desktop')
metainfo-dst := base-dir / 'share' / 'metainfo' / (appid + '.metainfo.xml')
icon-dst := base-dir / 'share' / 'icons' / 'hicolor' / 'scalable' / 'apps' / (appid + '.svg')
launcher-bin-dst := base-dir / 'bin' / launcher
# pop-launcher discovers plugins under share/pop-launcher/plugins/<name>/.
launcher-plugin-dst := base-dir / 'share' / 'pop-launcher' / 'plugins' / name / 'plugin.ron'

# Default recipe which runs `just build-release`
default: build-release

# Everything CI runs, in the order that fails cheapest first.
check-all: fmt-check check test validate-metadata

# Runs `cargo clean`
clean:
    cargo clean

# Removes vendored dependencies
clean-vendor:
    rm -rf .cargo vendor vendor.tar

# `cargo clean` and removes vendored dependencies
clean-dist: clean clean-vendor

# Compiles with debug profile
build-debug *args:
    cargo build --locked {{args}}

# Compiles with release profile
build-release *args: (build-debug '--release' args)

# Compiles release profile with vendored dependencies
build-vendored *args: vendor-extract (build-release '--frozen --offline' args)

# Runs a clippy check
check *args:
    cargo clippy --all-features --all-targets {{args}} -- -D warnings

# Runs a clippy check with JSON message format
check-json: (check '--message-format=json')

# Checks formatting without changing anything.
#
# `-p circle`, never `--all`: cosmic-pim is a *path* dependency, so `--all`
# reaches through it and reformats the substrate's source in its own checkout.
# That silently rewrites another repository — including whatever is uncommitted
# in it — as a side effect of formatting this one.
fmt-check:
    cargo fmt -p circle -- --check

# Formats the source. Same scoping rule as `fmt-check`.
fmt:
    cargo fmt -p circle

# Runs the test suite
test *args:
    cargo test {{args}}

# Validates the GENERATED desktop entry and AppStream metadata.
#
# Deliberately validates the build output rather than the templates: the
# templates are not themselves valid installable files once xdgen is in the
# picture, and it is the generated pair that ends up on a user's disk.
validate-metadata: build-debug
    desktop-file-validate {{desktop-src}}
    appstreamcli validate --no-net {{metainfo-src}}

# The same AppStream validation with the network reachability pass. Not run on
# pull requests, where the icon URL points at a branch that is not merged yet.
validate-metadata-urls: build-debug
    appstreamcli validate {{metainfo-src}}

# Run the application for testing purposes
run *args:
    env RUST_BACKTRACE=full cargo run --release {{args}}

# Run against sample data, leaving the real address book alone.
run-sandboxed dir='/tmp/circle-contacts': build-release
    mkdir -p {{dir}}
    env COSMIC_PIM_CONTACTS_DIR={{dir}} RUST_BACKTRACE=full {{ cargo-target-dir / 'release' / name }}

# Installs files, then refreshes the two caches that will not notice a new
# file on their own — "Open With" reads the first, the icon grid the second.
# Skipped when staging into a rootdir: the packager's postinst owns that.
install: build-release
    install -Dm0755 {{ cargo-target-dir / 'release' / name }} {{bin-dst}}
    install -Dm0755 {{ cargo-target-dir / 'release' / launcher }} {{launcher-bin-dst}}
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{metainfo-src}} {{metainfo-dst}}
    install -Dm0644 {{icon-src}} {{icon-dst}}
    install -Dm0644 {{launcher-plugin-src}} {{launcher-plugin-dst}}
    if [ -z '{{rootdir}}' ]; then \
        update-desktop-database {{ base-dir / 'share' / 'applications' }} || true; \
        gtk-update-icon-cache -f -t {{ base-dir / 'share' / 'icons' / 'hicolor' }} || true; \
    fi

# Uninstalls installed files
uninstall:
    rm -f {{bin-dst}} {{launcher-bin-dst}} {{desktop-dst}} {{metainfo-dst}} {{icon-dst}} {{launcher-plugin-dst}}

# Vendor dependencies locally
vendor:
    mkdir -p .cargo
    cargo vendor | head -n -1 > .cargo/config.toml
    echo 'directory = "vendor"' >> .cargo/config.toml
    tar pcf vendor.tar vendor
    rm -rf vendor

# Extracts vendored dependencies
vendor-extract:
    rm -rf vendor
    tar pxf vendor.tar
