# SPDX-License-Identifier: GPL-3.0-only

# Name of the application's binary.
name := 'circle'
launcher := 'circle-launcher'
# The unique ID of the application.
appid := 'com.magnetaros.Circle'

# Path to root file system, which defaults to `/`.
rootdir := ''
# The prefix for the `/usr` directory.
prefix := '/usr'
# The location of the cargo target directory. build.rs writes the generated
# XDG files under the same root, so redirecting it keeps everything together.
cargo-target-dir := env('CARGO_TARGET_DIR', 'target')

# Sources. The desktop entry and metainfo are GENERATED by build.rs from the
# templates in `resources/` plus the Fluent catalogues in `i18n/`, so the files
# installed below only exist after a build. `install` depends on that.
desktop-src := cargo-target-dir / 'xdgen' / 'app.desktop'
metainfo-src := cargo-target-dir / 'xdgen' / 'app.metainfo.xml'
icon-dir := 'resources' / 'icons' / 'hicolor'
icon-src := icon-dir / 'scalable' / 'apps' / (appid + '.svg')
icon-symbolic-src := icon-dir / 'symbolic' / 'apps' / (appid + '-symbolic.svg')
# The scalable SVG is what modern toolkits pick up; the PNGs are rasterised
# from it at each size so the panel and the icon grid get pixel-exact art
# instead of a downscaled smudge.
icon-sizes := '16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512'
launcher-plugin-src := 'resources' / 'launcher' / 'plugin.ron'

# Install destinations
base-dir := absolute_path(clean(rootdir / prefix))
bin-dst := base-dir / 'bin' / name
desktop-dst := base-dir / 'share' / 'applications' / (appid + '.desktop')
metainfo-dst := base-dir / 'share' / 'metainfo' / (appid + '.metainfo.xml')
icons-dst := base-dir / 'share' / 'icons' / 'hicolor'
icon-dst := icons-dst / 'scalable' / 'apps' / (appid + '.svg')
icon-symbolic-dst := icons-dst / 'symbolic' / 'apps' / (appid + '-symbolic.svg')
launcher-bin-dst := base-dir / 'bin' / launcher
# pop-launcher discovers plugins under share/pop-launcher/plugins/<name>/.
launcher-plugin-dst := base-dir / 'share' / 'pop-launcher' / 'plugins' / name / 'plugin.ron'

# Default recipe which runs `just build-release`
default: build-release

# Everything CI runs, in the order that fails cheapest first.
check-all: fmt-check check test validate-metadata

# `check-all`, but against a clean checkout of HEAD instead of the working tree.
#
# The working tree is not what CI sees, and in a checkout several sessions
# share it is not what anyone sees. The failure this exists for: a source file
# names a path — `include_bytes!` here, the icon lists in the flatpak manifest
# — that resolves only because an *untracked* file happens to sit at it. That
# compiles on this machine and fails on every clone. Circle shipped exactly
# that state for twenty commits. No test can find it, because tests run where
# the file is; only a checkout without your untracked files can.
#
# Also asserts what `git status` cannot: that the ignore rules deciding what
# is invisible live in the repository rather than in a developer's global
# config, since a rule in `~/.config/git/ignore` bounds a different set on
# every machine.
verify-head:
    #!/usr/bin/env bash
    set -euo pipefail

    # A stranger's view: global excludes disabled, so the only thing hidden is
    # what the repository itself hides. Anything listed here is either really
    # untracked, or ignored by a rule in someone's `~/.config/git/ignore` —
    # which bounds a different set on every machine, and so cannot be relied
    # on to say what a clone contains. Both want reporting; neither is
    # distinguishable from the other from inside this checkout.
    #
    # Comparing the two views is the point. Listing what the *local* view
    # ignores would be vacuous: with global excludes off, everything still
    # listed as ignored is by construction ignored by `.gitignore`, so the
    # assertion could never fail.
    stranger=$(git -c core.excludesFile=/dev/null status --porcelain -uall | sed -n 's/^?? //p')
    if [ -n "$stranger" ]; then
        echo "a clean clone would see these as untracked:"
        echo "$stranger" | sed 's/^/  /'
        echo "either commit them, or ignore them with a rule in .gitignore"
        exit 1
    fi

    pim=$(cd ../cosmic-pim 2>/dev/null && pwd) \
        || { echo "../cosmic-pim is missing; the path dependencies cannot resolve"; exit 1; }

    # Share this checkout's target directory. What is being isolated is the
    # *source* — a fresh target rebuilds libcosmic into /tmp and fills it —
    # and nothing here is decided by a build artefact: `include_bytes!` reads
    # the source tree, and cargo fingerprints the worktree's own path anyway,
    # so `circle` is rebuilt from the checkout under test either way.
    export CARGO_TARGET_DIR="$(pwd)/{{cargo-target-dir}}/verify-head"
    root=$(mktemp -d)
    trap 'git worktree remove --force "$root/circle" >/dev/null 2>&1 || true; rm -rf "$root"' EXIT

    # The worktree sits one level down so `../cosmic-pim` resolves the way it
    # does in a real side-by-side checkout, without writing into /tmp's root.
    ln -s "$pim" "$root/cosmic-pim"
    git worktree add --detach --quiet "$root/circle" HEAD

    cd "$root/circle"
    channel=$(sed -n 's/^channel *= *"\(.*\)"/\1/p' rust-toolchain.toml)
    manifest=$(sed -n 's/^rust-version *= *"\(.*\)"/\1/p' Cargo.toml)
    [ "$channel" = "$manifest" ] \
        || { echo "rust-toolchain.toml pins $channel; Cargo.toml declares $manifest"; exit 1; }
    cargo metadata --locked --format-version 1 >/dev/null

    just check-all
    echo "HEAD is what it claims to be."

# Runs `cargo clean`
clean:
    cargo clean

# Removes vendored dependencies
clean-vendor:
    rm -rf .cargo vendor vendor.tar

# `cargo clean` and removes vendored dependencies
clean-dist: clean clean-vendor

# Compiles with debug profile
build-debug *args:
    cargo build --locked {{args}}

# Compiles with release profile
build-release *args: (build-debug '--release' args)

# Compiles release profile with vendored dependencies
build-vendored *args: vendor-extract (build-release '--frozen --offline' args)

# Runs a clippy check
check *args:
    cargo clippy --all-features --all-targets {{args}} -- -D warnings

# Runs a clippy check with JSON message format
check-json: (check '--message-format=json')

# Checks formatting without changing anything.
#
# `-p circle`, never `--all`: cosmic-pim is a *path* dependency, so `--all`
# reaches through it and reformats the substrate's source in its own checkout.
# That silently rewrites another repository — including whatever is uncommitted
# in it — as a side effect of formatting this one.
fmt-check:
    cargo fmt -p circle -- --check

# Formats the source. Same scoping rule as `fmt-check`.
fmt:
    cargo fmt -p circle

# Runs the test suite
test *args:
    cargo test {{args}}

# Validates the GENERATED desktop entry and AppStream metadata.
#
# Deliberately validates the build output rather than the templates: the
# templates are not themselves valid installable files once xdgen is in the
# picture, and it is the generated pair that ends up on a user's disk.
validate-metadata: build-debug
    desktop-file-validate {{desktop-src}}
    appstreamcli validate --no-net {{metainfo-src}}

# The same AppStream validation with the network reachability pass. Not run on
# pull requests, where the icon URL points at a branch that is not merged yet.
validate-metadata-urls: build-debug
    appstreamcli validate {{metainfo-src}}

# Run the application for testing purposes
run *args:
    env RUST_BACKTRACE=full cargo run --release {{args}}

# Run against sample data, leaving the real address book alone.
run-sandboxed dir='/tmp/circle-contacts': build-release
    mkdir -p {{dir}}
    env COSMIC_PIM_CONTACTS_DIR={{dir}} RUST_BACKTRACE=full {{ cargo-target-dir / 'release' / name }}

# Installs files, then refreshes the two caches that will not notice a new
# file on their own — "Open With" reads the first, the icon grid the second.
# Skipped when staging into a rootdir: the packager's postinst owns that.
install: build-release
    install -Dm0755 {{ cargo-target-dir / 'release' / name }} {{bin-dst}}
    install -Dm0755 {{ cargo-target-dir / 'release' / launcher }} {{launcher-bin-dst}}
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{metainfo-src}} {{metainfo-dst}}
    install -Dm0644 {{icon-src}} {{icon-dst}}
    install -Dm0644 {{icon-symbolic-src}} {{icon-symbolic-dst}}
    for size in {{icon-sizes}}; do \
        install -Dm0644 {{icon-dir}}/$size/apps/{{appid}}.png \
            {{icons-dst}}/$size/apps/{{appid}}.png; \
    done
    install -Dm0644 {{launcher-plugin-src}} {{launcher-plugin-dst}}
    if [ -z '{{rootdir}}' ]; then \
        update-desktop-database {{ base-dir / 'share' / 'applications' }} || true; \
        gtk-update-icon-cache -f -t {{ base-dir / 'share' / 'icons' / 'hicolor' }} || true; \
    fi

# Uninstalls installed files
uninstall:
    rm -f {{bin-dst}} {{launcher-bin-dst}} {{desktop-dst}} {{metainfo-dst}} {{icon-dst}} {{launcher-plugin-dst}}
    rm -f {{icon-symbolic-dst}}
    for size in {{icon-sizes}}; do \
        rm -f {{icons-dst}}/$size/apps/{{appid}}.png; \
    done

# Vendor dependencies locally
vendor:
    mkdir -p .cargo
    cargo vendor | head -n -1 > .cargo/config.toml
    echo 'directory = "vendor"' >> .cargo/config.toml
    tar pcf vendor.tar vendor
    rm -rf vendor

# Extracts vendored dependencies
vendor-extract:
    rm -rf vendor
    tar pxf vendor.tar
