# SPDX-License-Identifier: GPL-3.0-only

# Name of the application's binary.
name := 'circle'
launcher := 'circle-launcher'
# The unique ID of the application.
appid := 'com.magnetaros.Circle'

# Path to root file system, which defaults to `/`.
rootdir := ''
# The prefix for the `/usr` directory.
prefix := '/usr'
# The location of the cargo target directory. build.rs writes the generated
# XDG files under the same root, so redirecting it keeps everything together.
cargo-target-dir := env('CARGO_TARGET_DIR', 'target')

# Sources. The desktop entry and metainfo are GENERATED by build.rs from the
# templates in `resources/` plus the Fluent catalogues in `i18n/`, so the files
# installed below only exist after a build. `install` depends on that.
desktop-src := cargo-target-dir / 'xdgen' / 'app.desktop'
metainfo-src := cargo-target-dir / 'xdgen' / 'app.metainfo.xml'
icon-dir := 'resources' / 'icons' / 'hicolor'
icon-src := icon-dir / 'scalable' / 'apps' / (appid + '.svg')
icon-symbolic-src := icon-dir / 'symbolic' / 'apps' / (appid + '-symbolic.svg')
# The scalable SVG is what modern toolkits pick up; the PNGs are rasterised
# from it at each size so the panel and the icon grid get pixel-exact art
# instead of a downscaled smudge.
icon-sizes := '16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512'
launcher-plugin-src := 'resources' / 'launcher' / 'plugin.ron'

# Install destinations
base-dir := absolute_path(clean(rootdir / prefix))
bin-dst := base-dir / 'bin' / name
desktop-dst := base-dir / 'share' / 'applications' / (appid + '.desktop')
metainfo-dst := base-dir / 'share' / 'metainfo' / (appid + '.metainfo.xml')
icons-dst := base-dir / 'share' / 'icons' / 'hicolor'
icon-dst := icons-dst / 'scalable' / 'apps' / (appid + '.svg')
icon-symbolic-dst := icons-dst / 'symbolic' / 'apps' / (appid + '-symbolic.svg')
launcher-bin-dst := base-dir / 'bin' / launcher
# pop-launcher discovers plugins under share/pop-launcher/plugins/<name>/.
launcher-plugin-dst := base-dir / 'share' / 'pop-launcher' / 'plugins' / name / 'plugin.ron'

# Default recipe which runs `just build-release`
default: build-release

# Everything CI runs, in the order that fails cheapest first.
check-all: fmt-check check test validate-metadata preflight-selftest

# Proves each preflight check fails on the input it exists for. On `check-all`
# rather than beside it, because a gate nobody is obliged to run is a practice.
preflight-selftest:
    ./scripts/preflight-selftest.sh

# `check-all`, but against a clean checkout of HEAD instead of the working tree.
#
# The working tree is not what CI sees, and in a checkout several sessions
# share it is not what anyone sees. The failure this exists for: a source file
# names a path — `include_bytes!` here, the icon lists in the flatpak manifest
# — that resolves only because an *untracked* file happens to sit at it. That
# compiles on this machine and fails on every clone. Circle shipped exactly
# that state for twenty commits. No test can find it, because tests run where
# the file is; only a checkout without your untracked files can.
#
# Also asserts what `git status` cannot: that the ignore rules deciding what
# is invisible live in the repository rather than in a developer's global
# config, since a rule in `~/.config/git/ignore` bounds a different set on
# every machine.
verify-head:
    #!/usr/bin/env bash
    set -euo pipefail

    # A stranger's view: global excludes disabled, so the only thing hidden is
    # what the repository itself hides. Anything listed here is either really
    # untracked, or ignored by a rule in someone's `~/.config/git/ignore` —
    # which bounds a different set on every machine, and so cannot be relied
    # on to say what a clone contains. Both want reporting; neither is
    # distinguishable from the other from inside this checkout.
    #
    # Comparing the two views is the point. Listing what the *local* view
    # ignores would be vacuous: with global excludes off, everything still
    # listed as ignored is by construction ignored by `.gitignore`, so the
    # assertion could never fail.
    stranger=$(git -c core.excludesFile=/dev/null status --porcelain -uall | sed -n 's/^?? //p')
    if [ -n "$stranger" ]; then
        echo "a clean clone would see these as untracked:"
        echo "$stranger" | sed 's/^/  /'
        echo "either commit them, or ignore them with a rule in .gitignore"
        exit 1
    fi

    # `git archive` rather than a worktree: it writes exactly the tracked files
    # at HEAD and nothing else, which is the definition being tested — what a
    # clone contains. A worktree can carry strays, and leaves bookkeeping that
    # `cargo clean` would orphan. It also stamps every file with the *commit*
    # time rather than the time of extraction, so re-extracting an unchanged
    # HEAD leaves cargo's mtime fingerprints intact and the build is
    # incremental; a worktree checkout stamps "now" and rebuilds everything.
    #
    # Both paths are fixed rather than `mktemp`, because cargo fingerprints a
    # crate by its source path: a fresh directory per run rebuilt `circle` and
    # every test binary from scratch, ninety seconds whether or not anything
    # had changed, and a gate that slow before a push is a gate nobody runs.
    # Sharing this checkout's dependency build is safe here — nothing under
    # test is decided by an artefact, since `include_bytes!` reads the source.
    verify="$(pwd)/{{cargo-target-dir}}/verify-head"
    export CARGO_TARGET_DIR="$verify/build"
    tree="$verify/tree"

    rm -rf "$tree"
    mkdir -p "$tree/circle"
    git archive --format=tar HEAD | tar -x -C "$tree/circle"

    cd "$tree/circle"
    # The same preflight CI runs, against the extracted tree rather than
    # this one. `--locked` follows it: preflight only reads files, where
    # `--locked` resolves the graph, and "your lock names a crate CI cannot
    # fetch" is a more actionable failure than "your lock is out of date".
    ./scripts/preflight.sh

    # preflight only reads files; this resolves the graph, so it is what
    # catches a lockfile that no longer describes the manifest at HEAD.
    cargo metadata --locked --format-version 1 >/dev/null || {
        echo
        echo "Cargo.lock at HEAD does not describe the graph that resolves today."
        echo "Run cargo check and commit the lockfile alongside the manifest."
        exit 1
    }

    just check-all
    echo "HEAD is what it claims to be."

# Runs `cargo clean`
clean:
    cargo clean

# Removes vendored dependencies
clean-vendor:
    rm -rf .cargo vendor vendor.tar

# `cargo clean` and removes vendored dependencies
clean-dist: clean clean-vendor

# Compiles with debug profile
build-debug *args:
    cargo build --locked {{args}}

# Compiles with release profile
build-release *args: (build-debug '--release' args)

# Compiles release profile with vendored dependencies
build-vendored *args: vendor-extract (build-release '--frozen --offline' args)

# Runs a clippy check
check *args:
    cargo clippy --all-features --all-targets {{args}} -- -D warnings

# Runs a clippy check with JSON message format
check-json: (check '--message-format=json')

# Checks formatting without changing anything.
#
# `-p circle` rather than `--all`. The substrate resolves from crates.io now,
# so `--all` no longer reaches into a sibling checkout, but naming the package
# keeps that true if a `[patch]` is ever uncommented for local work — which
# would put the substrate's working tree back in this workspace.
fmt-check:
    cargo fmt -p circle -- --check

# Formats the source. Same scoping rule as `fmt-check`.
fmt:
    cargo fmt -p circle

# Runs the test suite
test *args:
    cargo test {{args}}

# Validates the GENERATED desktop entry and AppStream metadata.
#
# Deliberately validates the build output rather than the templates: the
# templates are not themselves valid installable files once xdgen is in the
# picture, and it is the generated pair that ends up on a user's disk.
validate-metadata: build-debug
    desktop-file-validate {{desktop-src}}
    appstreamcli validate --no-net {{metainfo-src}}

# The same AppStream validation with the network reachability pass. Not run on
# pull requests, where the icon URL points at a branch that is not merged yet.
validate-metadata-urls: build-debug
    appstreamcli validate {{metainfo-src}}

# Run the application for testing purposes
run *args:
    env RUST_BACKTRACE=full cargo run --release {{args}}

# Run against sample data, leaving the real address book alone.
run-sandboxed dir='/tmp/circle-contacts': build-release
    mkdir -p {{dir}}
    env COSMIC_PIM_CONTACTS_DIR={{dir}} RUST_BACKTRACE=full {{ cargo-target-dir / 'release' / name }}

# Installs files, then refreshes the two caches that will not notice a new
# file on their own — "Open With" reads the first, the icon grid the second.
# Skipped when staging into a rootdir: the packager's postinst owns that.
install: build-release
    install -Dm0755 {{ cargo-target-dir / 'release' / name }} {{bin-dst}}
    install -Dm0755 {{ cargo-target-dir / 'release' / launcher }} {{launcher-bin-dst}}
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{metainfo-src}} {{metainfo-dst}}
    install -Dm0644 {{icon-src}} {{icon-dst}}
    install -Dm0644 {{icon-symbolic-src}} {{icon-symbolic-dst}}
    for size in {{icon-sizes}}; do \
        install -Dm0644 {{icon-dir}}/$size/apps/{{appid}}.png \
            {{icons-dst}}/$size/apps/{{appid}}.png; \
    done
    install -Dm0644 {{launcher-plugin-src}} {{launcher-plugin-dst}}
    if [ -z '{{rootdir}}' ]; then \
        update-desktop-database {{ base-dir / 'share' / 'applications' }} || true; \
        gtk-update-icon-cache -f -t {{ base-dir / 'share' / 'icons' / 'hicolor' }} || true; \
    fi

# Uninstalls installed files
uninstall:
    rm -f {{bin-dst}} {{launcher-bin-dst}} {{desktop-dst}} {{metainfo-dst}} {{icon-dst}} {{launcher-plugin-dst}}
    rm -f {{icon-symbolic-dst}}
    for size in {{icon-sizes}}; do \
        rm -f {{icons-dst}}/$size/apps/{{appid}}.png; \
    done

# Vendor dependencies locally
vendor:
    mkdir -p .cargo
    cargo vendor | head -n -1 > .cargo/config.toml
    echo 'directory = "vendor"' >> .cargo/config.toml
    tar pcf vendor.tar vendor
    rm -rf vendor

# Extracts vendored dependencies
vendor-extract:
    rm -rf vendor
    tar pxf vendor.tar
